### PR TITLE
lndconnect/zap support

### PR DESCRIPTION
**Pull request by manecosta**
### `lnd.conf`
- Adding `tlxextraip` property pointing to the local network ip.
- Changing `rpclisten` to `0.0.0.0` from `localhost` to accept external connections.

### `lndconnect.py`
New service with some helper methods to generate the `lndconnect` urls.

### Zap
Old buttons were replaced with 2 new ones:
- Open Zap Desktop - Opens the zap desktop application using an `lndconnect` link.
- Show QR Code - Shows a new window with a QR Code that can be used to connect Zap iOS application.

### Requirements
- Added `qrcode` and `pillow` to support the QR Code functionality.

### Misc
- Added a title to the main window `Node Launcher`.
- Set `debuglevel` of lnd to `info`

## Addresses:
- #81
- #54 

## Known issues:
- `tlsextraip` is currently set to the local network ip which limits connectivity for the iOS app for within the same local network.
- Upon update, users need to remove `tls.cert` and `tls.key` files so that `lnd` generates them again with the added `tlsextraip`.

### CODE REVIEW

**Comment by PierreRochard** [comment]
image

Getting this error

**Comment by manecosta** [comment]
I didn't test it on MacOS as I didn't have one available. On windows it worked well. Can you test on windows to see if it's an OS issue?

**Comment by mrfelton** [comment]
There is an issue here in that Zap Desktop doesn't currently handle the lndconnect links if the app is not currently open (this is the cause of the error shown above). We hope to have a fix for this included in the next release of Zap Desktop.

**Comment by manecosta** [comment]
> There is an issue here in that Zap Desktop doesn't currently handle the lndconnect links if the app is not currently open (this is the cause of the error shown above). We hope to have a fix for this included in the next release of Zap Desktop.

Cool, then I guess there's nothing else to do here.

**Pull request merged**
